buildscript {
    project.ext.version = [
            'major': 1,
            'minor': 4,
            'patch': 1,
    ]

    project.ext.version['name'] = "${project.ext.version.major}.${project.ext.version.minor}.${project.ext.version.patch}"
    project.ext.version['code'] = project.ext.version.major * 10000000 + project.ext.version.minor * 10000 + project.ext.version.patch
}

plugins {
    id 'com.android.application'
}

android {
    namespace 'id.thony.android.quranlite'
    compileSdkVersion 36
    defaultConfig {
        applicationId "id.thony.android.quranlite"
        minSdkVersion 18
        targetSdkVersion 36
        versionCode project.ext.version.code
        versionName "${project.ext.version.name}"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compileOnly 'org.jetbrains:annotations:26.0.2-1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}
